name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload a Build Artifact # Name of the step
        uses: actions/upload-artifact@v4 # Action to use
        with: # Parameters for the action
          name: code
          path: .
  Lint:
    runs-on: ubuntu-latest
    needs: ['Build']
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code 
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
